analyzers:
- providers:
  - archan.CSVFileProvider:
      file_path: path/to/my/file.csv
      delimiter: ","
  checkers:
  - archan.LayeredArchitecture
  - archan.OpenDesign:
      pass: true
  - archan.EconomyOfMechanism:
      independence_factor: 2
- providers:
  - dependenpy.ArchanProvider:
        packages:
        - path/to/my/package
        - python_package
        depth: 1
  checkers: archan.LayeredArchitecture
- archan.DependencyAnalyzer
