language: python
python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"
    - "3.4"
install:
- pip install pep8
- pip install pyflakes
- pip install pylint
- pip install coveralls
before_script:
- ./tests.sh
script:
- coverage run archan/tests.py
- coverage report -m
after_success: coveralls
