analyzers:
- providers:
  - dependenpy.InternalDependencies:
      packages:
      - archan
  checkers:
  - archan.CodeClean
  - archan.CompleteMediation
  - archan.EconomyOfMechanism:
      independence_factor: 4
  - archan.LayeredArchitecture
  - archan.LeastCommonMechanism
  - archan.OpenDesign:
      ok: true
