analyzers:
  - name: General
    providers:
      - archan_pylint.MessagesPerModule:
          pylint_args:
            - src/archan
    checkers:
      - archan.OpenDesign:
          ok: true
      - archan.CodeClean:
          threshold: 10
          ignore: true
  - name: Internal software dependencies
    providers:
      - dependenpy.InternalDependencies:
          packages:
            - src/archan
    checkers:
      - archan.CompleteMediation
      - archan.EconomyOfMechanism:
          simplicity_factor: 2
          ignore: true
      - archan.LayeredArchitecture
      - archan.LeastCommonMechanism:
          independence_factor: 5
          ignore: true
