analyzers:
- providers:
  - dependenpy.InternalDependencies:
      packages:
      - archan
  checkers:
  - archan.CompleteMediation
  - archan.EconomyOfMechanism:
      simplicity_factor: 2
  - archan.LayeredArchitecture
  - archan.LeastCommonMechanism:
      independence_factor: 5
  - archan.OpenDesign:
      ok: true
